// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4XtbZL2eAyyb5T__54DareTbJIsXn1AU',
    appId: '1:760313286028:web:8f564ca28a2be3a2471aa9',
    messagingSenderId: '760313286028',
    projectId: 'jual-bibit',
    authDomain: 'jual-bibit.firebaseapp.com',
    storageBucket: 'jual-bibit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr_KrGyFK45ugwrKGS1sbIY6tX4Bp5JXw',
    appId: '1:760313286028:android:d4e570aabbca4ed9471aa9',
    messagingSenderId: '760313286028',
    projectId: 'jual-bibit',
    storageBucket: 'jual-bibit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9I72E1DKv7xdmKkcocXy0ZwC0L-xyit8',
    appId: '1:760313286028:ios:a8b2c3f23569419c471aa9',
    messagingSenderId: '760313286028',
    projectId: 'jual-bibit',
    storageBucket: 'jual-bibit.firebasestorage.app',
    iosBundleId: 'com.example.adminQurbanMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9I72E1DKv7xdmKkcocXy0ZwC0L-xyit8',
    appId: '1:760313286028:ios:a8b2c3f23569419c471aa9',
    messagingSenderId: '760313286028',
    projectId: 'jual-bibit',
    storageBucket: 'jual-bibit.firebasestorage.app',
    iosBundleId: 'com.example.adminQurbanMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4XtbZL2eAyyb5T__54DareTbJIsXn1AU',
    appId: '1:760313286028:web:14e08a692c8a16db471aa9',
    messagingSenderId: '760313286028',
    projectId: 'jual-bibit',
    authDomain: 'jual-bibit.firebaseapp.com',
    storageBucket: 'jual-bibit.firebasestorage.app',
  );
}
